services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"

  api:
    image: ewallet-api
    build:
      context: ..
      dockerfile: test_api_jwt/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=EWalletDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
      - ConnectionStrings__Redis=redis:6379

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # البورت الأساسي اللي الكود بيكلم منه الرابيت
      - "15672:15672" # بورت شاشة التحكم (UI)